fix(impound): set vehicle props reliably
Qbox-project/qbx_police pull request #119
Opened 2024-06-08 08:32 UTC by solareon

## Description

qbx.spawnVehicle supports props so we need to send these to the server to set on the vehicle via statebag. Additionally the arguments for the spawn are out of order for impound cars resulting in keys not being given when pulling from impound.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-06-08 08:38 UTC, Manason requested changes

2024-06-08 08:38 UTC, Manason commented on client/job.lua
> +    local properties = lib.callback.await('qb-garage:server:GetVehicleProperties', false, vehicle.plate)
We shouldn't be call backing to another resource. Need to expose an export from qbx_garages, or otherwise have all impounded vehicles owned by policejob.

2024-06-08 09:48 UTC, FjamZoo commented on server/main.lua
> +lib.callback.register('qbx_policejob:server:spawnVehicle', function(source, model, coords, plate, giveKeys, vehId, vehProps)
I really hate this, anyone can spawn their vehicle of choice, why is there no server validation for job etc and possible grade if some are limited to that?


I know its out of scope for this PR but its VERY fucking wierd.

2024-06-08 10:18 UTC, solareon commented on client/job.lua
> +    local properties = lib.callback.await('qb-garage:server:GetVehicleProperties', false, vehicle.plate)
fixed. blocked until https://github.com/Qbox-project/qbx_vehicles/pull/5 is merged.

2024-06-08 10:18 UTC, solareon commented on server/main.lua
> +lib.callback.register('qbx_policejob:server:spawnVehicle', function(source, model, coords, plate, giveKeys, vehId, vehProps)
added guard condition for this.

2024-06-13 15:42 UTC, Manason commented on client/job.lua
> +    local properties = lib.callback.await('qb-garage:server:GetVehicleProperties', false, vehicle.plate)
You can use exports.qbx_vehicles:GetPlayerVehicles now

2024-06-13 17:50 UTC, solareon commented on client/job.lua
> +    local properties = lib.callback.await('qb-garage:server:GetVehicleProperties', false, vehicle.plate)
We do that? Please check the last commit. This was before I refactored it

2024-06-13 18:04 UTC, Manason approved these changes

2024-06-13 18:04 UTC, Manason commented on client/job.lua
>      doCarDamage(veh, vehicle)
I think we can get rid of these two calls. When the vehicle is spawned the vehicle properties are set, which would include fuel level and previously saved damage. Can be done in a different PR.

2024-06-13 18:05 UTC, Manason commented on client/job.lua
> +    local properties = lib.callback.await('qb-garage:server:GetVehicleProperties', false, vehicle.plate)
Ah, yes all looks good now. Looks like we're still doing a bunch of unnecessary work after the vehicle entity exists that I believe would be handled by passing the props already, but that can be ripped out in a subsequent PR.

2024-06-13 18:07 UTC, Manason requested changes

2024-06-13 18:07 UTC, Manason commented on server/main.lua
> +    end
Replace with qbx_vehicles:GetPlayerVehicle

ideally we look up the vehicle by vehicleId rather than plate as well.

2024-09-09 12:06 UTC, solareon commented
Being fixed in refactor

2024-09-09 12:06 UTC, closed without merging