Customize the blip in a better
Qbox-project/qbx_police pull request #99
Opened 2024-03-31 19:40 UTC by bicatcho11

## Description

Customize the blip in a better

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-04-24 19:13 UTC, KostaZx approved these changes

2024-04-24 19:37 UTC, Manason requested changes
This introduces unused config values

2024-05-02 20:57 UTC, BerkieBb requested changes

2024-05-02 20:57 UTC, BerkieBb commented on client/main.lua
> +    for i, station in ipairs(config.locations.stations) do
1. the `i` is not used
2. use a numeric for loop instead

2024-09-10 01:22 UTC, mafewtm commented
Going to be customizable in the rewrite.

2024-09-10 01:22 UTC, closed without merging